name: ci

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: continuous integration process
                run: bash test_case/test.sh